### ISSUE TITLE
Prefix delimiter comes after suffix delimiter

### ISSUE THREAD

**Issue by ishtiaque06** [ishtiaque06/vh-fst#33]
@therringsh 

Your test(s) for igbo have `+` after `-`. I'm assuming that this is a mix-up of using python's f-strings and normal string concatenation. 

https://github.com/ishtiaque06/vh-fst/blob/3955347d438e1572e4693958b4c879229396f5eb/tests/test_fst.py#L372

**Comment by ishtiaque06** [comment]
In your commit for the fix, add 'resolves #33'. Thanks!

**Comment by therringsh** [comment]
I think I did that to test impossible transitions where + follows -, but
given you check for that anyways, you can remove the pluses at the end and
run the tests.

**Comment by ishtiaque06** [comment]
Sounds good!
