### ISSUE TITLE
(9, 'i') doesn't have next state.

### ISSUE THREAD

**Issue by ishtiaque06** [ishtiaque06/vh-fst#37]
@therringsh 

https://github.com/ishtiaque06/vh-fst/blob/361d3b3d4bc1734b52b15b6374b774cdfac6445c/vh_patterns_dataset.py#L2204

**Comment by therringsh** [comment]
9 = next state; I'll make the change on my branch

**Comment by ishtiaque06** [comment]
Okay. Please close this issue when done.
