### ISSUE TITLE
Missing next state: 34P, Yawelmani

### ISSUE THREAD

**Issue by ishtiaque06** [ishtiaque06/vh-fst#39]
@therringsh 

what state does `(2,'?'):('i?')` lead to?

https://github.com/ishtiaque06/vh-fst/blob/ba908ad23d6792ecfd6cc39486a54775877f5bed/vh_patterns_dataset.py#L2263

**Comment by therringsh** [comment]
feeds back into 2; I made the change in the Travis branch; The transitions seem okay for 34P and 34B regarding '#', so we'll have to get together regarding the reason # is at the end of outputs
